trigger:
- master

pool:
  name: Default

steps:
- script: docker --version
  displayName: "Check Docker"

- script: docker info
  displayName: "Docker Info"

- script: docker build -t my-nginx-app .
  displayName: "Build Docker Image"

- script: docker images
  displayName: "List Images"

- script: docker run -d --name my-nginx-container -p 8080:80 my-nginx-app
  displayName: "Run Docker Container"

- script: docker ps
  displayName: "Running Containers"